[tool.ruff]
line-length = 88
fix = false
indent-width = 2

[tool.ruff.lint]
select = ["F", "C", "W", "I"]
ignore = ["E203", "E501", "F401", "C408", "F811", "N807"]

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
docstring-code-line-length = 88